// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://imcrcsgfobvimwndzylr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImltY3Jjc2dmb2J2aW13bmR6eWxyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwNzcxMTYsImV4cCI6MjA3NDY1MzExNn0.8808gRpwgrE-nHJS7asR1GvNeksgCZ8Vgk69IHjzL8g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);